### 8.1 텍스트 분석
- 비정형 텍스트에서 의미 있는 정보를 추출하는 것

  ex) 텍스트 분류, 감성 분석, 텍스트 요약, 텍스트 군집화/유사도 ...
- NLP : 머신이 인간의 언어를 이해하고 해석하는 데 더 중점을 두고 기술이 발전

- 피처 벡터화/ 피처 추출 : 텍스트 변환 - 텍스트 word 기반의 다수의 피처로 추출하고 이 피처에 단어 빈도수와 같은 숫자 값을 부여하면 텍스트는 단어의 조합인 벡터값으로 표현될 수 있음.
  > BOW, word2vec

- 텍스트 분석 수행 프로세스
> ` 1) 텍스트 사전 준비작업(텍스트 전처리)`
> > 대/소문자 변경, 특수문자 삭제 등의 클렌징 작업
>
> > 의미 없는 단어 제거 작업, 단어 등의 토큰화 작업
>
> > 어근 추출 등의 텍스트 정규화 작업
>
> ` 2) 피처 벡터화/추출 `
> > 사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 여기에 벡터 값을 할당
>
> > BOW (COUNT 기반, TF-IDF) / Word2Vec
>
> ` 3) ML 모델 수립 및 학습/예측/평가 `
> > 피처 벡터화된 데이터 세트에 ML 모델을 적용해 학습/예측 및 평가를 수행


### 8.2 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화


- 클렌징
> - 텍스트에서 분석에 오히려 방해가 되는 불필요한 문자, 기호 등을 사전에 제거하는 작업.
> - ex) html, xml 태그나 특정 기호 등을 사전에 제거함

- 텍스트 토큰화
> - 토큰화의 유형은 문서에서 문장을 분리하는 문장 토큰화와 문장에서 단어를 토큰으로 분리하는 단어 토큰화로 나눌 수 있음.
> - `(1) 문장 토큰화` : 문장의 마침표, 개행문자 등 문장의 마지막을 뜻하는 기호에 따라 분리하는 것이 일반적. 정규 표현식에 따른 문장 토큰화도 가능.
> - `(2) 단어 토큰화` : 문장을 단어로 토큰화. 기본적으로 공백, 콤마, 마침표, 개행문자 등의 단어를 분리. 정규표현식을 이용해 다양한 유형으로 토큰화 가능.
> - 일반적으로 문장 토큰화는 각 문장이 가지는 시멘틱적인 의미가 중요한 경우 사용.
> - 단어의 순서가 중요하지 않은 경우 문장 토큰화를 사용하지 않고 단어의 토큰화만 사용해도 충분함.
> - 단어 토큰화의 한계를 보완한 것이 N-GRAM > N개 단어 크기 윈도우를 만들어 문장의 처음부터 오른쪽으로 움직이면서 토큰화 수행

- 스톱워드 제거
> - 스톱워드 : 분석에 큰 의미가 없는 단어 (EX: is, the, a, will 등 문법 요소)
> - 스톱워드는 빈번하게 텍스트에 발생함으로 중요한 단어로 간주될 수 있음
> - NTLK : 언어별 스톱 워드 목록를 제공

- Stemming, Lemmatization
> - 많은 언어에서 문법적인 요소에 따라 단어가 다양하게 변함 -> 원형 단어를 찾아주는 목적으로 사용됨
> - Stemming 단순한 방법을 적용해 원래 단어에서 일부 철자가 훼손된 어근 단어를 추출하는 경향 있음
> - Lemmatization이 Stemming 보다 정교하며 의미론적인 기반에서 단어의 원형을 찾음. 품사와 같은 문법적인 요소와 더 의미적인 부분을 감안해 정확한 철자로 된 어근 단어를 찾아줌. Stemming보다 변환에 더 오랜 시간이 소요.

### 8.3 Bag of Words

- Bag of Words 모델
> - 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델
> - 문서 내 모든 단어를 한꺼번에 봉투(Bag) 안에 넣은 뒤에 흔들어서 섞는다는 의미로 BOW 모델이라고 함.
> - `피처 벡터화 방법` : 모든 문서에서 모든 단어를 칼럼 형태로 나열하고 각 문서에 해당하는 단어의 횟수나 정규화된 빈도를 값으로 부여하는 데이터 세트 모델로 변경하는 것.
- 장점
- > 쉽고 빠른 구축. 단순히 단어의 발생 횟수에 기반하지만, 예상 보다 문서의 특징을 잘 나타낼 수 있는 모델
- 단점
- > (1) 문맥의미 반영 부족 (2) 희소 행렬 문제(알고리즘의 수행시간과 예측 성능을 떨어뜨림)

- 방법
> - `1) 카운트 기반 벡터화` : 단어 피처에 값을 부여 시 각 문서에서 해당 단어가 나타나는 횟수를 부여
> - `2) TF-IDF` : 개별 문서에서 자주 나타나는 단어에 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어에는 패널티를 줌
> > 개별 문서에서의 단어 빈도 * log ( 전체 문서의 갯수 / 단어 i를 가지고 있는 문서의 갯수 )

- 희소행렬 보완 방법
> 희소행렬의 경우 물리적으로 적은 메모리 공간을 차지할 수 있도록 변환해야함
> - `1) COO 형식`
> > 0이 아닌 데이터만 별도의 데이터 배열에 저장하고 그 데이터가 가리키는 행과 열의 위치를 별도의 배열에 저장하는 것.
> - `2) CSR 형식`
> > - COO 형식이 행과 열의 위치를 나타내기 위해서 반복적인 위치 데이터를 사용해야하는 문제점을 해결한 방식.
> > - COO 형식의 행과 열 위치 배열을 다시 고유값의 시작 위치만 담긴 배열로 변경하여 메모리 적게 들게 함.
>


### Text Tokenization

In [1]:
from nltk import sent_tokenize

import nltk
nltk.download('punkt')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to C:\Users\kt
[nltk_data]     NexR\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [2]:
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [3]:
from nltk import word_tokenize, sent_tokenize

#여러개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화 만드는 함수 생성
def tokenize_text(text):
    
    # 문장별로 분리 토큰
    sentences = sent_tokenize(text)
    # 분리된 문장별 단어 토큰화
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

#여러 문장들에 대해 문장별 단어 토큰화 수행. 
word_tokens = tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


### Stopwords 제거

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\kt
[nltk_data]     NexR\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
print('영어 stop words 갯수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 갯수: 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [7]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
# 위 예제의 3개의 문장별로 얻은 word_tokens list 에 대해 stop word 제거 Loop
for sentence in word_tokens:
    filtered_words=[]
    # 개별 문장별로 tokenize된 sentence list에 대해 stop word 제거 Loop
    for word in sentence:
        #소문자로 모두 변환합니다. 
        word = word.lower()
        # tokenize 된 개별 word가 stop words 들의 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)
    
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


### Stemming과 Lemmatization

In [8]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [9]:
from nltk.stem import WordNetLemmatizer

import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

[nltk_data] Downloading package wordnet to C:\Users\kt
[nltk_data]     NexR\AppData\Roaming\nltk_data...


amuse amuse amuse
happy happy
fancy fancy


## 8.3 Bag of Words – BOW

### 희소 행렬 - COO 형식

In [11]:
import numpy as np

dense = np.array( [ [ 3, 0, 1 ], [0, 2, 0 ] ] )

In [12]:
from scipy import sparse

# 0 이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

In [13]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

### 희소 행렬 – CSR 형식

In [14]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

# 0 이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환 
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())


COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [15]:
dense3 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)